### ISSUE TITLE
Project / WP setup

### ISSUE THREAD

**Issue by gracecanfield** [nationalpublicmedia/npm-website#3]
**Tasks:**

* [x] Craft data setup
* [x] Build tools setup
* [ ] Hook up Craft w/ asset CDN (?)
* [x] CSS system setup

**Comment by justinvandenberg** [comment]
@gracecanfield did we decide if they'll be using a CDN on the WordPress site? It doesn't look like they are on the current site.

**Comment by gracecanfield** [comment]
@justinvandenberg I'm actually not sure (but I _think_ we wouldn't be using one?). We should confirm with @yaychris when he gets back next Tuesday.
